name = "ReactionTest"
uuid = "52296e94-2442-4a8c-af1d-005e75a38201"
authors = ["Alexander Reimer <alexander.reimer2357@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
